# Generated by Django 5.0.14 on 2025-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFESOR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='especializacion',
            field=models.CharField(choices=[('P', 'psicopedagogo'), ('T', 'Trastornos de la escritura'), ('N', 'neuroeducación aplicada al TDAH')], max_length=1),
        ),
    ]
