# Generated by Django 5.0.14 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(choices=[('D', 'Disgrafia'), ('T', 'TDA'), ('DC', 'Discalculia')], max_length=2)),
            ],
        ),
    ]
