# Generated by Django 5.0.14 on 2025-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niño',
            name='contraseña',
            field=models.CharField(max_length=64),
        ),
    ]
