# Generated by Django 5.0.14 on 2025-05-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0002_alter_niño_contraseña'),
        ('PADRE', '0002_alter_padre_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='niño',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='PADRE.padre'),
        ),
    ]
