# Generated by Django 5.0.14 on 2025-05-31 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0003_niño_padre'),
        ('PADRE', '0002_alter_padre_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niño',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='PADRE.padre'),
        ),
    ]
