# Generated by Django 5.0.14 on 2025-05-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0004_alter_niño_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='niño',
            name='codigo',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
