# Generated by Django 5.0.14 on 2025-05-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0005_niño_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niño',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
