# Generated by Django 5.0.14 on 2025-05-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIÑO', '0006_alter_niño_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distracciones', models.IntegerField(blank=True, help_text='Cantidad de distracciones detectadas', null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('duracion_evaluacion', models.DurationField(blank=True, help_text='Duración total de la evaluación', null=True)),
                ('niño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='NIÑO.niño')),
            ],
        ),
    ]
